arch:
    - amd64
    - arm64

language: python
install: echo "Not installing any requirements!"

services:
    - docker

before_install:
    - sudo apt-get install docker-compose

script:
    - docker-compose -f docker-compose.yml build

after_success:
    - if [ $TRAVIS_CPU_ARCH == "arm64" ] && [ $TRAVIS_BRANCH == "master" ]; then
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
        docker tag floofyjul/peach-bot:latest floofyjul/peach-bot:arm64-latest;
        docker rmi floofyjul/peach-bot:latest;
        docker push floofyjul/peach-bot:arm64-latest;
        docker tag floofyjul/peach-interface:latest floofyjul/peach-interface:arm64-latest;
        docker rmi floofyjul/peach-interface:latest;
        docker push floofyjul/peach-interface:arm64-latest;
        docker manifest create floofyjul/peach-interface:latest floofyjul/peach-interface:arm64-latest floofyjul/peach-interface:amd64-latest;
        docker manifest push floofyjul/peach-interface:latest;
        docker manifest create floofyjul/peach-bot:latest floofyjul/peach-bot:arm64-latest floofyjul/peach-bot:amd64-latest;
        docker manifest push floofyjul/peach-bot:latest;
        fi
    - if [ $TRAVIS_CPU_ARCH == "amd64" ] && [ $TRAVIS_BRANCH == "master" ]; then
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
        docker tag floofyjul/peach-bot:latest floofyjul/peach-bot:amd64-latest;
        docker rmi floofyjul/peach-bot:latest;
        docker push floofyjul/peach-bot:amd64-latest;
        docker tag floofyjul/peach-interface:latest floofyjul/peach-interface:amd64-latest;
        docker rmi floofyjul/peach-interface:latest;
        docker push floofyjul/peach-interface:amd64-latest;
        docker manifest create floofyjul/peach-interface:latest floofyjul/peach-interface:arm64-latest floofyjul/peach-interface:amd64-latest;
        docker manifest push floofyjul/peach-interface:latest;
        docker manifest create floofyjul/peach-bot:latest floofyjul/peach-bot:arm64-latest floofyjul/peach-bot:amd64-latest;
        docker manifest push floofyjul/peach-bot:latest;
        fi