arch:
    - amd64
    - arm64

language: python
install: echo "Not installing any requirements!"

services:
    - docker

before_install:
    - sudo apt-get install docker-compose

script:
    - docker-compose -f docker-compose.yml build

after_success:
    - on:
        arch: arm64
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    - docker tag floofyjul/peach-bot:latest floofyjul/peach-bot:arm-latest
    - docker rmi floofyjul/peach-bot:latest
    - docker push floofyjul/peach-bot:arm-latest
    - docker tag floofyjul/peach-interface:latest floofyjul/peach-interface:arm-latest
    - docker rmi floofyjul/peach-interface:latest
    - docker push floofyjul/peach-interface:arm-latest

before_install:
    - on:
        arch: amd64
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    - docker tag floofyjul/peach-bot:latest floofyjul/peach-bot:amd64-latest
    - docker rmi floofyjul/peach-bot:latest
    - docker push floofyjul/peach-bot:amd64-latest
    - docker tag floofyjul/peach-interface:latest floofyjul/peach-interface:amd64-latest
    - docker rmi floofyjul/peach-interface:latest
    - docker push floofyjul/peach-interface:amd64-latest