arch:
    - amd64
    - arm64

language: python

python:
    - "3.7"

services:
    - docker

install:
    - echo "Not installing requirements"

script:
    - docker-compose -f docker-compose.yml build