os: linux
dist: xenial

language: go

go:
  - 1.13.x

jobs:
  include:
  - stage: test
    script:
      - go get golang.org/x/tools/cmd/stringer
      - go mod download
      - go generate ./...
      - ./scripts/test.sh
  - stage: build
    script:
      - go get golang.org/x/tools/cmd/stringer
      - go mod download
      - go generate ./...
      - ./scripts/build.sh