os: linux
dist: xenial

language: go

go:
  - 1.13.x

install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

jobs:
  include:
  - stage: test
    script:
      - go get golang.org/x/tools/cmd/stringer
      - go mod download
      - go generate ./...
      - ./scripts/test.sh