arch:
    - amd64
    - arm

services:
    - docker

before_install:
    - sudo apt-get install docker-compose

script:
    - docker-compose -f docker-compose.yml build

after_success:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    - docker tag floofyjul/peach-bot:latest floofyjul/peach-bot:arm-latest
    - docker rmi floofyjul/peach-bot:latest
    - docker push floofyjul/peach-bot:arm-latest
    - docker tag floofyjul/peach-interface:latest floofyjul/peach-interface:arm-latest
    - docker rmi floofyjul/peach-interface:latest
    - docker push floofyjul/peach-interface:arm-latest
    - on:
        arch: arm