arch:
    - amd64
    - arm64

language: python

python:
    - "3.7"

services:
    - docker

before_install:
    - sudo apt-get install docker-compose

install:
    - echo "Not installing requirements"

script:
    - docker-compose -f docker-compose.yml build

after_success:
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push floofyjul/peach-bot:latest; 
    docker push floofyjul/peach-interface:latest;
    fi