version: "2"
services:
  eventHandler:
    image: sleepyjul/peach-event-handler:latest
    build:
      context: ./peach_event_handler
      dockerfile: ./Dockerfile

  trafficHandler:
    image: sleepyjul/peach-traffic-handler:latest
    build:
      context: ./peach_traffic_handler
      dockerfile: ./Dockerfile

  wsgi:
    image: sleepyjul/peach-wsgi-app:latest
    build:
      context: ./peach_wsgi_app
      dockerfile: ./Dockerfile
