version: "2"

services:
  database:
    image: postgres:11.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: peach
      POSTGRES_PASSWORD: peach
      POSTGRES_DB: peach
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    network_mode: "host"

  bot:
    image: floofyjul/peach-bot
    build:
      context: .
      dockerfile: ./Bot.Dockerfile
    environment:
      BOTTOKEN: MY_EPIC_BOT_TOKEN
      DBHOST: 0.0.0.0
      DBPORT: 5432
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    network_mode: "host"

  interface:
    image: floofyjul/peach-interface
    build:
      context: .
      dockerfile: ./Interface.Dockerfile
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    network_mode: "host"