version: "2"
services:
  bot:
    image: peachbot/peach:latest
    build: .
    ports: 
      - "5000:5000"
  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: peach
      POSTGRES_PASSWORD: peach
      POSTGRES_DB: peach
    volumes:
      - ./peachdbvol:/var/lib/postgresql/data

volumes:
    peachdbvol:
        external: true