version: "2"
services:
  eventHandler:
    image: peach/event-handler:latest
    build:
      context: ./peach_event_handler
      dockerfile: ./Dockerfile

  trafficHandler:
    image: peach/traffic-handler:latest
    build:
      context: ./peach_traffic_handler
      dockerfile: ./Dockerfile

  wsgi:
    image: peach/wsgi:latest
    build:
      context: ./peach_wsgi_app
      dockerfile: ./Dockerfile
