apiVersion: apps/v1
kind: Deployment
metadata:
  name: peach-event-handler
spec:
  selector:
    matchLabels:
      app: peach-event-handler
  template:
    metadata:
      labels:
        app: peach-event-handler
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: peach-event-handler
        image: sleepyjul/peach-event-handler
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: peach-event-handler
spec:
  type: ClusterIP
  selector:
    app: peach-event-handler
  ports:
  - name: peach-event-handler
    port: 5000
    targetPort: 8080