apiVersion: apps/v1
kind: Deployment
metadata:
  name: peach-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      name: interface
      labels:
        app: interface
    spec:
      containers:
      - name: peach-interface
        image: sleepyjul/peach-interface
        ports:
        - containerPort: 8080