apiVersion: apps/v1
kind: Deployment
metadata:
  name: peach-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      name: interface
      labels:
        app: interface
    spec:
      containers:
      - name: peach-interface
        image: sleepyjul/peach-interface
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: peach-interface
spec:
  type: NodePort 
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
    name: http
    protocol: TCP
  selector:
    app: interface